### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by cardosofelipe** [peppergaming/pepper-star-battle#2]
**AS A** Logged out User

**I WANT TO** be able to login into the game through a Login Page

**SO THAT** can access the game with my account and enjoy my game profile

**TASKS**:
- [x] Design of the page
- [x] Implement a clean and simple AuthProvider Context exposing all the authentication functions and state (login, logout, isLogged, isLoading, user,and so on)
- [x] Install the [pepper auth sdk](https://github.com/peppergaming/auth) and use it as authentication lib in the AuthProvider

**Comment by cardosofelipe** [comment]
Design of login component to be shown at the center of the page.
![image](https://user-images.githubusercontent.com/17471456/180213919-db40fa94-b169-4735-81df-66bced74ed12.png)

**Comment by AndreaRavano** [comment]
We can use the above form inside a modal, after clicking on login here:

![Starbattle intro - login](https://user-images.githubusercontent.com/18379363/181271588-22524a7a-acf4-4756-bf9c-38d2c0092fac.png)


Or put directly the form inside the view as here:

![Starbattle intro - direct login](https://user-images.githubusercontent.com/18379363/181271709-3c46975c-c809-4392-9f4f-cfbadc0cb317.png)


I suggest for the seek of the first release to choose the quickest to implement
