### ISSUE TITLE
Get an NFT when a game is over

### ISSUE THREAD

**Issue by cardosofelipe** [peppergaming/pepper-star-battle#6]
**WHEN** I finish my first game

**I WANT** to have a visual notification which tells me that I have received an NFT. The notification should include a link to the explorer so that I can check on-chain and should also tell me to go see the NFT on Pepper

**SO THAT** I understand that now I am the lucky holder of an NFT and I did't have to deal with any crypto shit to obtain it

**TASKS**:
- [x] Design of notification (maybe a modal?) @AndreaRavano 
- [ ] Implement in backend the NFT claim logic based on user score @Dibri (https://gitlab.com/Pepperzone/pepper-backend/-/issues/633)
- [x] Implement design and manage the NFT claim request @ggxforce

**Comment by AndreaRavano** [comment]
If you already received an NFT, the view should only display "replay" option:

![Starbattle Win - already claimed](https://user-images.githubusercontent.com/18379363/181281242-20995bde-8497-4970-8aa8-af121cb35e09.png)



NFT Drop view (to be claimed):

![Starbattle Win - NFT Drop](https://user-images.githubusercontent.com/18379363/181281388-feaa6bb0-608a-45ab-a5b9-a1ae07c61d29.png)


NFT Claimed successfully:

![Starbattle Win - NFT Claimed Success](https://user-images.githubusercontent.com/18379363/181281573-3f798314-36e6-4659-bee4-b88e3691e1ff.png)
